### ISSUE TITLE
how changes lp problem?

### ISSUE THREAD

**Issue by rlacjfjin** [lanl/clp#12]
Hi,
is it possible to get reduced cost?
And, changes the lp problem, such as add(delete) rows or columns?

**Comment by spakin** [comment]
> is it possible to get reduced cost?

I don't understand.  Are you asking about `SetOptimizationDirection`, which lets you select whether to minimize or maximize the objective function?

> And, changes the lp problem, such as add(delete) rows or columns?

You can use `AppendColumn` to append a column.  The `clp` package does not currently support appending rows or deleting rows or columns, but I don't believe this would be difficult to support.

**Comment by rlacjfjin** [comment]
Thanks,
the reduced cost defined as following:
reduced cost = obj - A^T * y 
where obj is the coefficients of the original LP,  and y is the vector of dual multipliers for the rows.

In fact, I want to write a MILP solver using golang, which is based on branch and cut algorithm.
And I want to have a LP solver interface to support the relaxation problem solving part.

Thanks a lot.

**Comment by spakin** [comment]
> the reduced cost defined as following:
> reduced cost = obj - A^T * y
> where obj is the coefficients of the original LP, and y is the vector of dual multipliers for the rows.

As the `clp` package is essentially just a wrapper for [COIN-OR's CLP module](https://www.coin-or.org/Clp), could you point me to the functions in the C API that I should wrap with Go to provide the reduced-cost functionality you're looking for?

**Comment by rlacjfjin** [comment]
Sorry,
I find the function which is returned reduced cost, named simplex_get_dual_col_soln. 
  double* simplex_get_dual_col_soln (clp_object* model)
  {
    return ((ClpSimplex*)model)->dualColumnSolution();
  }
In CLP, dualColumnSolution and getReducedCost are both returned reducedCost_.
I try to add some specific functions in my environment.
Thanks.

**Comment by spakin** [comment]
Do you mean that the `clp` package's [`Simplex.DualColumnSolution`](https://github.com/lanl/clp/blob/7958c4324310e216c765e2b858b1e12904fffea6/simplex.go#L313) already provides the functionality you're looking for?  Can I close this issue?

**Comment by rlacjfjin** [comment]
Yes, it's ok.

**Comment by spakin** [comment]
All right; thanks.
