### ISSUE TITLE
godoc not displaying package documentation due to unrecognized LICENSE

### ISSUE THREAD

**Issue by yonch** [lanl/clp#15]
Hi team!
Thank you for this package, looks like just what I was looking for.

The [godoc site](https://godoc.org/github.com/lanl/clp) for the package says:

Documentation not displayed due to license restrictions.
See our [license policy](https://pkg.go.dev/license-policy).

Looks like this is because the license has non-standard wording, and godoc now has a policy to only display docs for allowed licenses. Usually I would love to submit a pull request to fix, but licensing is up to the releasing authors/org. Do you think it would be possible to perhaps switch to one of the standard BSD N-clause licenses (perhaps with the government contract attribution in the README)?

**Comment by spakin** [comment]
> Looks like this is because the license has non-standard wording, and godoc now has a policy to only display docs for allowed licenses. Usually I would love to submit a pull request to fix, but licensing is up to the releasing authors/org. Do you think it would be possible to perhaps switch to one of the standard BSD N-clause licenses (perhaps with the government contract attribution in the README)?

That's exactly right: The wording is just different enough from BSD-3 that [pkg.go.dev](https://pkg.go.dev/github.com/lanl/clp) doesn't recognize it as such.  Unfortunately, LANL requires their specific wording of the license.  When you first opened this issue I asked go-discovery-feedback@google.com if there's some mechanism by which I can add a line to the LICENSE file that says, "I promise I'm BSD-3 so please don't bother checking."  Although in the past that address has led to quick responses, they haven't yet written back this time.  I suppose I should open a GitHub issue in case the email address is no longer being monitored.

**Comment by spakin** [comment]
With permission from my institution, I made [`LICENSE.md`](https://github.com/lanl/clp/blob/455f2bee2560bd23a8a90ed8d82fa4191f569ab5/LICENSE.md) a "pure" BSD 3-clause license and moved the problematic US Government rights paragraph into [`README.md`](https://github.com/lanl/clp/blob/455f2bee2560bd23a8a90ed8d82fa4191f569ab5/README.md).

See also the discussion at golang/go#52554.
