### ISSUE TITLE
clp-interface.cxx:1:10: fatal error: 'coin/ClpSimplex.hpp' file not found

### ISSUE THREAD

**Issue by smithla02** [lanl/clp#8]
Hello, I downloaded the latest distribution of [clp](https://github.com/coin-or/Clp) using [coinbrew](https://coin-or.github.io/coinbrew/) and the following script:
```bash
wget https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew
chmod u+x coinbrew
./coinbrew fetch Clp@master
./coinbrew build Clp
```

I have tried to download on both mac and linux. I have run into the following issue with the import in [clp-interface.cxx](https://github.com/lanl/clp/blob/master/clp-interface.cxx) in both systems:
``` bash
clp-interface.cxx:1:31: fatal error: coin/ClpSimplex.hpp: No such file or directory
 #include <coin/ClpSimplex.hpp>
```

Here is what I have tried in both systems.

## Linux 
The README says the library has only been tested in linux. To try to find the location of the clp library: 
``` bash
pkg-config --libs clp
-L/home/luissmith/dist/lib -lClp
```

If I try to find the `ClpSimplex.hpp` file on the machine, these are the results:
``` bash
find ~/ -type f -name ClpSimplex.hpp
/home/luissmith/Clp/src/ClpSimplex.hpp
/home/luissmith/dist/include/coin-or/ClpSimplex.hpp
```

Is the issue related to the path in one of the newer distributions of CLP? I am realizing the path here is `.../coin-or/ClpSimplex.hpp`, whereas in the [clp-interface.cxx](https://github.com/lanl/clp/blob/master/clp-interface.cxx) it is looking for `coin/ClpSimplex.hpp`?

I also needed to export the package path:
```bash
export LD_LIBRARY_PATH="/home/luissmith/dist/lib/"
export PKG_CONFIG_PATH="/home/luissmith/dist/lib/pkgconfig/"
```

If i type the command ```clp``` in command line, the response is:
```bash
Coin LP version devel, build Jul 26 2020
Clp takes input from arguments ( - switches to stdin)
Enter ? for list of commands or help
```

## Mac

To try to find the location of the clp library: 
``` bash
pkg-config --libs clp
-L/usr/local/Cellar/clp/1.17.3/lib -L/usr/local/Cellar/coinutils/2.11.3/lib -lClpSolver -lClp -lCoinUtils -lbz2 -lz -framework Accelerate -lm
```

If I try to find the `ClpSimplex.hpp` file on the machine, these are the results:
```bash
find ~/ -type f -name ClpSimplex.hpp
/Users/luissmith//dist/include/coin-or/ClpSimplex.hpp
/Users/luissmith//Clp/src/ClpSimplex.hpp
```

Is the issue related to the path in one of the newer distributions of CLP? I am realizing the path here is `.../coin-or/ClpSimplex.hpp`, whereas in the `clp-interface.cxx` file it is looking for `coin/ClpSimplex.hpp`?

If i type the command ```clp``` in command line, the response is:
```bash
Coin LP version 1.17.3, build Jul 19 2020
Clp takes input from arguments ( - switches to stdin)
Enter ? for list of commands or help
```

## Feedback
I would really appreciate any tips you have on debugging what might be going wrong. And please let me know if you need any more information from me. Thanks.

**Comment by smithla02** [comment]
It seems the issue was related to imports. I am not sure if it's related to the fact that I am using the latest version of CLP (Clp@1.17.6).

I was able to find a temporary workaround. You can see more details here: https://github.com/coin-or/Clp/issues/155#issuecomment-664271013

If you have any insights on the reasons behind the issue, do let me know. Thanks!

**Comment by spakin** [comment]
The good news is that the Ubuntu package (`coinor-libclp-dev`, version 1.17.5) works with both `#include <coin/ClpSimplex.hpp>` and `#include <ClpSimplex.hpp>`.  Should I change the former to the latter in `clp-interface.cxx` and commit that?

**Comment by tkralphs** [comment]
The `.pc` file has the full path to the directory where the headers are installed (including the final `coin` or `coin-or` subdirectory), so 
`#include <ClpSimplex.hpp>` seems to make sense. I don't actually see how the header file could be found with `pkg-config` if you do `#include <coin/ClpSimplex.hpp>`. The former has the advantage of being agnostic to the change in installation location that we made recently (and that will be the new default once a new stable version of Clp is released).

**Comment by spakin** [comment]
> I don't actually see how the header file could be found with `pkg-config` if you do `#include <coin/ClpSimplex.hpp>`.

Good question.  I just checked, and here's what I see on my Ubuntu 20.04 system:
```
$ pkg-config --cflags clp
-I/usr/include/coin
```
The answer is therefore that `#include <ClpSimplex.hpp>` is finding the file from `pkg-config`'s `-I/usr/include/coin`, and `#include <coin/ClpSimplex.hpp>` is finding it via ordinary `/usr/include`.

**Comment by tkralphs** [comment]
Ah yes, that makes sense.

**Comment by smithla02** [comment]
Thank you @spakin! I appreciate your prompt response and fixing the issue
